// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/app-link/index.vue')['default']
    ColorPicker: typeof import('./src/components/color-picker/index.vue')['default']
    DaterangePicker: typeof import('./src/components/daterange-picker/index.vue')['default']
    DelWrap: typeof import('./src/components/del-wrap/index.vue')['default']
    DictValue: typeof import('./src/components/dict-value/index.vue')['default']
    Editor: typeof import('./src/components/editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FooterBtns: typeof import('./src/components/footer-btns/index.vue')['default']
    Icon: typeof import('./src/components/icon/index.vue')['default']
    IconPicker: typeof import('./src/components/icon/picker.vue')['default']
    IconSvgIcon: typeof import('./src/components/icon/svg-icon.vue')['default']
    ImageContain: typeof import('./src/components/image-contain/index.vue')['default']
    Link: typeof import('./src/components/link/index.vue')['default']
    LinkCustomLink: typeof import('./src/components/link/custom-link.vue')['default']
    LinkPicker: typeof import('./src/components/link/picker.vue')['default']
    LinkShopPages: typeof import('./src/components/link/shop-pages.vue')['default']
    Material: typeof import('./src/components/material/index.vue')['default']
    MaterialFile: typeof import('./src/components/material/file.vue')['default']
    MaterialPicker: typeof import('./src/components/material/picker.vue')['default']
    MaterialPreview: typeof import('./src/components/material/preview.vue')['default']
    OverflowTooltip: typeof import('./src/components/overflow-tooltip/index.vue')['default']
    Pagination: typeof import('./src/components/pagination/index.vue')['default']
    PopoverInput: typeof import('./src/components/popover-input/index.vue')['default']
    Popup: typeof import('./src/components/popup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/upload/index.vue')['default']
    VideoPlayer: typeof import('./src/components/video-player/index.vue')['default']
  }
}

export {}
